### ISSUE TITLE
RuntimeError: Failed to fetch any data from dataloader after refresh.

### ISSUE THREAD

**Issue by ovvo20** [DLYuanGod/TinyGPT-V#30]
When I trained the stage4, I met an error. How to address it?

Train: data epoch: [0]  [   0/1000]  eta: 2:15:24  lr: 0.000001  loss: 10.6312  time: 8.1247  data: 0.0000  max mem: 9246
Train: data epoch: [0]  [  50/1000]  eta: 0:30:10  lr: 0.000001  loss: 8.0872  time: 0.6961  data: 0.0000  max mem: 15709
Traceback (most recent call last):
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/datasets/datasets/dataloader_utils.py", line 159, in __next__
    data = next(self.iter_loader)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/datasets/datasets/dataloader_utils.py", line 163, in __next__
    data = next(self.iter_loader)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/Project/TinyGPT-V/train.py", line 104, in <module>
    main()
  File "/root/autodl-tmp/Project/TinyGPT-V/train.py", line 100, in main
    runner.train()
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/runners/runner_base.py", line 377, in train
    train_stats = self.train_epoch(cur_epoch)
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/runners/runner_base.py", line 437, in train_epoch
    return self.task.train_epoch(
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/tasks/base_task.py", line 116, in train_epoch
    return self._train_inner_loop(
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/tasks/base_task.py", line 207, in _train_inner_loop
    samples = next(data_loader)
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/datasets/datasets/dataloader_utils.py", line 45, in __next__
    return next(self.loaders[loader_idx])
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/datasets/datasets/dataloader_utils.py", line 165, in __next__
    raise RuntimeError('Failed to fetch any data from dataloader after refresh.')
RuntimeError: Failed to fetch any data from dataloader after refresh.

**Comment by llizhaoxu** [comment]
Hi

It may be caused by a setting error in the dataloader; could you please check which dataset got wrong in detail?
