### ISSUE TITLE
stage4 train torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by ovvo20** [DLYuanGod/TinyGPT-V#32]
when i use 4*RTX4090 24G GPU to train the stage4:
torchrun --nproc-per-node 4 train.py --cfg-path train_configs/tinygptv_stage4.yaml > training_log.txt 2>&1

I met the error, can you help me, thank you:
Traceback (most recent call last):
  File "/root/autodl-tmp/Project/TinyGPT-V/train.py", line 104, in <module>
    main()
  File "/root/autodl-tmp/Project/TinyGPT-V/train.py", line 100, in main
    runner.train()
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/runners/runner_base.py", line 377, in train
    train_stats = self.train_epoch(cur_epoch)
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/runners/runner_base.py", line 437, in train_epoch
    return self.task.train_epoch(
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/tasks/base_task.py", line 116, in train_epoch
    return self._train_inner_loop(
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/tasks/base_task.py", line 221, in _train_inner_loop
    loss = self.train_step(model=model, samples=samples)
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/tasks/base_task.py", line 70, in train_step
    loss = model(samples)["loss"]
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/Project/TinyGPT-V/minigpt4/models/minigpt_base.py", line 302, in forward
    outputs = self.llama_model(
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/peft/peft_model.py", line 530, in forward
    return self.base_model(
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/transformers/models/phi/modeling_phi.py", line 1064, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/transformers/models/phi/modeling_phi.py", line 941, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/transformers/models/phi/modeling_phi.py", line 681, in forward
    attn_outputs, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/transformers/models/phi/modeling_phi.py", line 394, in forward
    attn_weights = nn.functional.softmax(attn_weights, dtype=torch.float32, dim=-1).to(query_states.dtype)
  File "/root/miniconda3/envs/tinygptv/lib/python3.9/site-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 154.00 MiB (GPU 0; 23.65 GiB total capacity; 22.19 GiB already allocated; 128.06 MiB free; 22.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ovvo20** [comment]
the gpu status:
<img width="442" alt="image" src="https://github.com/DLYuanGod/TinyGPT-V/assets/122522813/37574f17-f3f5-4bcc-b871-6219dc961943">

**Comment by ovvo20** [comment]
I modified the codes in the base_model.py line183:
if low_resource:
    llama_model = PhiForCausalLM.from_pretrained(
        llama_model_path,
        torch_dtype=torch.float16,
        load_in_8bit=True,
        device_map = {'': 'auto'}
I changed the device_map={'': low_res_device} to the device_map = {'': 'auto'}, it also didn't work. I have no idea how to address it.
